### PR TITLE
Update XdebugVersion.php

### LINKED ISSUE #89: /wizard gives incorrect instruction for installing on windows
After pasting my phpinfo(), I was prompted to add `zend_extension = ext\php_xdebug-2.9.6-7.4-vc15-x86_64.dll` to my php.ini.

This doesn't work; the correct line to use was  `zend_extension = php_xdebug-2.9.6-7.4-vc15-x86_64.dll`.

My stock php.ini file appears to have extension_dir set to ext:

```
; Directory in which the loadable extensions (modules) reside.
; http://php.net/extension-dir
;extension_dir = "./"
; On windows:
extension_dir = "ext"
```

### PR DESCRIPTION
**Pull request by wenz**
Probably fixes #89

### CODE REVIEW

**Review by derickr — CHANGES_REQUESTED** [review]
This patch is most certainly not correct, as it misses the equivalent check in line 410. In any case, what needs to happen is to check whether the value in `$this->extensionDir` is a relative path or an absolute path. If it's absolute, it should include it, if it's relative, it should not  — regardless of whether you're on Windows or not.

**Comment by wenz** [comment]
Sorry for dropping the ballon this. Good catch with line 410. But I still don't understand why we should use absolute paths at all. When we load an extension with path or filename "x", PHP tries to load the physical file extension_dir + "x". The installation instructions recommend putting the Xdebug extension in the extension dir anyway. So regardless of whether the extension_dir is set to an absolute path, or a relativ path, or not set at all, just using the file name of the extension works in all cases IMO.

**Comment by derickr** [comment]
Absolute paths were required in the PHP 5 days for zend extensions, so that's why the instructions have that. Are you interested in fixing this PR so that I can merge it?

**Comment by wenz** [comment]
Will do - since PHP 5 is not supported any longer, we go with the relative paths, right?

**Comment by derickr** [comment]
Yes, that's fine.

**Review by lastthyme — APPROVED** [review]

**Comment by derickr** [comment]
I think this PR is no longer relevant, as I've recently updated the logic. I'm therefore closing it.

**Pull request closed without merging**
